#!/bin/bash
if [ -z "$PATH" ]; then
    bkuppaths="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
else
    bkuppaths="$PATH"
fi

argcount=0
stoptrying=false
arguments=$@
for argument in "$@"; do
    if [[ "$1" = "-u" ]] || [[ "$1" = "-w" ]] || [[ "$1" = "-m" ]] || [[ "$1" = "-S" ]] || [[ "$1" = "--user" ]] || [[ "$1" = "--description" ]] || [[ "$1" = "--message" ]]; then
        shift
        shift
    elif [[ "$argument" = "--" ]]; then
        shift
    fi
done
arguments="$@"
#Remove the bits arguments before the executable command with sed
echo "GKSU is depreciated. Please move to PKEXEC."
pkexec env org.freedesktop.policykit.exec.allow_gui=TRUE DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY $arguments
exit $?
